services:
  postgres:
    image: postgres:16
    container_name: lawyer-ryu-pg
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lawyer-ryu
    volumes:
      - lawyer-ryu-pg-data:/var/lib/postgresql/data

volumes:
  lawyer-ryu-pg-data:
